spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memdb
    username: ohgiraffers
    password: ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: DXEMF06fL20Py67dy9pp
            client-secret: 89Y9atEqvW
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          google:
            client-id: 62790710914-0uj632naot18b9s7vq28inn1122l506o.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8


server:
  port: 80

