spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: DXEMF06fL20Py67dy9pp
            client-secret: 89Y9atEqvW
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  thymeleaf:
    cache: false

server:
  port: 80
